# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2.1"

services:

  validator-0:
    build:
      context: ../../..
      dockerfile: ./validator/Dockerfile
    image: sawtooth-validator$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    command: "bash -c \"\
        sawadm keygen --force && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
            --endpoint tcp://validator-0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5005 \
    \""
    stop_signal: SIGKILL

  validator-1:
    build:
      context: ../../..
      dockerfile: ./validator/Dockerfile
    image: sawtooth-validator$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    depends_on:
      - validator-0
    command: "bash -c \"\
        sawadm keygen --force && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5005 \
          --peers tcp://validator-0:8800
    \""
    stop_signal: SIGKILL

  validator-2:
    build:
      context: ../../..
      dockerfile: ./validator/Dockerfile
    image: sawtooth-validator$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    depends_on:
      - validator-0
      - validator-1
    command: "bash -c \"\
        sawadm keygen --force && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-2:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5005 \
          --peers tcp://validator-1:8800
    \""
    stop_signal: SIGKILL

  validator-3:
    build:
      context: ../../..
      dockerfile: ./validator/Dockerfile
    image: sawtooth-validator$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    depends_on:
      - validator-0
      - validator-1
    command: "bash -c \"\
        sawadm keygen --force && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5005 \
          --peers tcp://validator-1:8800
    \""
    stop_signal: SIGKILL

  validator-4:
    build:
      context: ../../..
      dockerfile: ./validator/Dockerfile
    image: sawtooth-validator$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    depends_on:
      - validator-2
      - validator-3
    command: "bash -c \"\
        sawadm keygen --force && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-4:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5005 \
          --peers tcp://validator-2:8800,tcp://validator-3:8800
    \""
    stop_signal: SIGKILL

  devmode-0:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator-0:5005 -v
    stop_signal: SIGKILL

  devmode-1:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator-1:5005 -v
    stop_signal: SIGKILL

  devmode-2:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator-2:5005 -v
    stop_signal: SIGKILL

  devmode-3:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator-3:5005 -v
    stop_signal: SIGKILL

  devmode-4:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator-4:5005 -v
    stop_signal: SIGKILL

  rest-api-0:
    build:
      context: ../../..
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-rest-api$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-0:4004 --bind rest-api-0:8008
    stop_signal: SIGKILL

  rest-api-1:
    build:
      context: ../../..
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-rest-api$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL

  rest-api-2:
    build:
      context: ../../..
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-rest-api$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-2:4004 --bind rest-api-2:8008
    stop_signal: SIGKILL

  rest-api-3:
    build:
      context: ../../..
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-rest-api$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-3:4004 --bind rest-api-3:8008
    stop_signal: SIGKILL

  rest-api-4:
    build:
      context: ../../..
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-rest-api$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-4:4004 --bind rest-api-4:8008
    stop_signal: SIGKILL

  settings-tp-0:
    build:
      context: ../../..
      dockerfile: ./families/settings/Dockerfile
    image: sawtooth-settings-tp$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp -v -C tcp://validator-0:4004
    stop_signal: SIGKILL

  settings-tp-1:
    build:
      context: ../../..
      dockerfile: ./families/settings/Dockerfile
    image: sawtooth-settings-tp$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp -v -C tcp://validator-1:4004
    stop_signal: SIGKILL

  settings-tp-2:
    build:
      context: ../../..
      dockerfile: ./families/settings/Dockerfile
    image: sawtooth-settings-tp$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp -v -C tcp://validator-2:4004
    stop_signal: SIGKILL

  settings-tp-3:
    build:
      context: ../../..
      dockerfile: ./families/settings/Dockerfile
    image: sawtooth-settings-tp$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp -v -C tcp://validator-3:4004
    stop_signal: SIGKILL

  settings-tp-4:
    build:
      context: ../../..
      dockerfile: ./families/settings/Dockerfile
    image: sawtooth-settings-tp$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp -v -C tcp://validator-4:4004
    stop_signal: SIGKILL

  test-peer-list:
    build:
      context: ../../..
      dockerfile: integration/sawtooth_integration/docker/integration-tests.dockerfile
    image: integration-tests:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 8008
    command: nose2-3
        -c /project/sawtooth-core/integration/sawtooth_integration/nose2.cfg
        -v
        -s /project/sawtooth-core/integration
        sawtooth_integration.tests.test_peer_list.TestPeerList
    stop_signal: SIGKILL
