# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2.1"

services:

  track-and-trade-tp:
    image: sawtooth-track-and-trade-tp:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: track-and-trade-tp -vv -C tcp://validator:4004
    stop_signal: SIGKILL

  rethinkdb:
    image: rethinkdb
    expose:
      - 8008
      - 28015

  tnt-server:
    image: track-and-trade-server:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 8008
      - 3000
    depends_on:
      - rethinkdb
    command: "bash -c \" \
        set -x && \
        cd /project/sawtooth-core/families/track_and_trade/server && \
        npm link bcrypt body-parser express js-schema jsonwebtoken lodash protobufjs sawtooth-sdk rethinkdb && \
        DB_HOST=rethinkdb node ./scripts/bootstrap_database.js && \
        VALIDATOR_URL=tcp://validator:4004 DB_HOST=rethinkdb node index.js
    \""

  settings-tp:
    image: sawtooth-settings-tp:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
    command: settings-tp tcp://validator:4004
    stop_signal: SIGKILL

  validator:
    image: sawtooth-validator:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    depends_on:
      - tnt-server
    command: "bash -c \"\
        sawadm keygen && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawadm genesis config-genesis.batch && \
        sawadm genesis && \
        sawtooth-validator -v \
            --endpoint tcp://validator:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5005 \
    \""
    stop_signal: SIGKILL

  devmode:
    build:
      context: ../../..
      dockerfile: ./sdk/examples/devmode_rust/Dockerfile
    image: sawtooth-devmode$INSTALL_TYPE:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    working_dir: /project/sawtooth-core/sdk/examples/devmode_rust
    command: devmode-engine-rust --connect tcp://validator:5005 -v
    stop_signal: SIGKILL

  rest-api:
    image: sawtooth-rest-api:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 4004
      - 8009
    command: sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8009
    stop_signal: SIGKILL

  test-track-and-trade:
    image: sawtooth-dev-python:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    expose:
      - 8008
      - 8009
    depends_on:
      - tnt-server
    command: "bash -c \" \
        sleep 5 && \
        nose2-3
        -c /project/sawtooth-core/integration/sawtooth_integration/nose2.cfg
        -v
        -s /project/sawtooth-core/integration/sawtooth_integration/tests
        test_track_and_trade.TestTrackAndTrade
    \""
    stop_signal: SIGKILL
    environment:
      PYTHONPATH: "/project/sawtooth-core/sdk/python:\
        /project/sawtooth-core/families/track_and_trade/processor:\
        /project/sawtooth-core/families/track_and_trade/tests:\
        /project/sawtooth-core/integration:\
        /project/sawtooth-core/signing"
