# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f sdk/cxx/Dockerfile-installed -t sawtooth-sdk-cxx.

# -------------=== cxx sdk build ===-------------

FROM ubuntu:xenial as cxx-sdk-builder

ENV VERSION=AUTO_STRICT

RUN echo "deb http://repo.sawtooth.me/ubuntu/ci xenial universe" >> /etc/apt/sources.list \
 && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 && apt-get update \
 && apt-get install -y -q \
    apt-transport-https \
    autoconf  \
    automake  \
    build-essential \
    ca-certificates \
    cmake  \
    curl \
    git \
    g++  \
    libcrypto++-dev \
    liblog4cxx-dev \
    libtool \
    libzmqpp-dev \
    libffi-dev \
    libssl-dev \
    make \
    protobuf \
    python3-pip \
    unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
    cpplint

COPY . /project

RUN cd /project/ \
 && export sawtooth_version=$(bin/get_version) \
 && export sawtooth_major="$(echo $sawtooth_version | cut -d "." -f 1)" \
 && export sawtooth_minor="$(echo $sawtooth_version | cut -d "." -f 2)" \
 && export sawtooth_patch1="$(echo $sawtooth_version | cut -d "." -f 3)" \
 && export sawtooth_patch2="$(echo $sawtooth_version | cut -d "." -f 4)" \
 && if [ -z $sawtooth_patch2 ]; then export sawtooth_patch=$sawtooth_patch1; else export sawtooth_patch="$sawtooth_patch1.$sawtooth_patch2"; fi \
 && cd /project/sdk/cxx \
 && mkdir -p build \
 && cd build \
# To build with debug symbols use:
# cmake -DCMAKE_BUILD_TYPE=Debug ..
 && cmake .. \
 && make \
 && make package

# -------------=== cxx sdk docker build ===-------------

FROM ubuntu:xenial

COPY --from=cxx-sdk-builder /project/sdk/cxx/build/ sawtooth-cxx-sdk-*.deb /tmp

RUN echo "deb http://repo.sawtooth.me/ubuntu/ci xenial universe" >> /etc/apt/sources.list \
 && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 && apt-get update \
 && dpkg -i /tmp/sawtooth-*.deb || true \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
