// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client_transaction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from client_transaction.proto</summary>
public static partial class ClientTransactionReflection {

  #region Descriptor
  /// <summary>File descriptor for client_transaction.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ClientTransactionReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhjbGllbnRfdHJhbnNhY3Rpb24ucHJvdG8aEXRyYW5zYWN0aW9uLnByb3Rv",
          "GhljbGllbnRfbGlzdF9jb250cm9sLnByb3RvIpUBChxDbGllbnRUcmFuc2Fj",
          "dGlvbkxpc3RSZXF1ZXN0Eg8KB2hlYWRfaWQYASABKAkSFwoPdHJhbnNhY3Rp",
          "b25faWRzGAIgAygJEiUKBnBhZ2luZxgDIAEoCzIVLkNsaWVudFBhZ2luZ0Nv",
          "bnRyb2xzEiQKB3NvcnRpbmcYBCADKAsyEy5DbGllbnRTb3J0Q29udHJvbHMi",
          "zgIKHUNsaWVudFRyYW5zYWN0aW9uTGlzdFJlc3BvbnNlEjUKBnN0YXR1cxgB",
          "IAEoDjIlLkNsaWVudFRyYW5zYWN0aW9uTGlzdFJlc3BvbnNlLlN0YXR1cxIi",
          "Cgx0cmFuc2FjdGlvbnMYAiADKAsyDC5UcmFuc2FjdGlvbhIPCgdoZWFkX2lk",
          "GAMgASgJEiUKBnBhZ2luZxgEIAEoCzIVLkNsaWVudFBhZ2luZ1Jlc3BvbnNl",
          "IpkBCgZTdGF0dXMSEAoMU1RBVFVTX1VOU0VUEAASBgoCT0sQARISCg5JTlRF",
          "Uk5BTF9FUlJPUhACEg0KCU5PVF9SRUFEWRADEgsKB05PX1JPT1QQBBIPCgtO",
          "T19SRVNPVVJDRRAFEhIKDklOVkFMSURfUEFHSU5HEAYSEAoMSU5WQUxJRF9T",
          "T1JUEAcSDgoKSU5WQUxJRF9JRBAIIjUKG0NsaWVudFRyYW5zYWN0aW9uR2V0",
          "UmVxdWVzdBIWCg50cmFuc2FjdGlvbl9pZBgBIAEoCSLQAQocQ2xpZW50VHJh",
          "bnNhY3Rpb25HZXRSZXNwb25zZRI0CgZzdGF0dXMYASABKA4yJC5DbGllbnRU",
          "cmFuc2FjdGlvbkdldFJlc3BvbnNlLlN0YXR1cxIhCgt0cmFuc2FjdGlvbhgC",
          "IAEoCzIMLlRyYW5zYWN0aW9uIlcKBlN0YXR1cxIQCgxTVEFUVVNfVU5TRVQQ",
          "ABIGCgJPSxABEhIKDklOVEVSTkFMX0VSUk9SEAISDwoLTk9fUkVTT1VSQ0UQ",
          "BRIOCgpJTlZBTElEX0lEEAhCMQoVc2F3dG9vdGguc2RrLnByb3RvYnVmUAFa",
          "FmNsaWVudF90cmFuc2FjdGlvbl9wYjJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::TransactionReflection.Descriptor, global::ClientListControlReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientTransactionListRequest), global::ClientTransactionListRequest.Parser, new[]{ "HeadId", "TransactionIds", "Paging", "Sorting" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientTransactionListResponse), global::ClientTransactionListResponse.Parser, new[]{ "Status", "Transactions", "HeadId", "Paging" }, null, new[]{ typeof(global::ClientTransactionListResponse.Types.Status) }, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientTransactionGetRequest), global::ClientTransactionGetRequest.Parser, new[]{ "TransactionId" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientTransactionGetResponse), global::ClientTransactionGetResponse.Parser, new[]{ "Status", "Transaction" }, null, new[]{ typeof(global::ClientTransactionGetResponse.Types.Status) }, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// A request to return a list of txns from the validator. May include the id
/// of a particular block to be the `head` of the chain being requested. In that
/// case the list will include the txns from that block, and all txns
/// previous to that block on the chain. Filter with specific `transaction_ids`.
/// </summary>
public sealed partial class ClientTransactionListRequest : pb::IMessage<ClientTransactionListRequest> {
  private static readonly pb::MessageParser<ClientTransactionListRequest> _parser = new pb::MessageParser<ClientTransactionListRequest>(() => new ClientTransactionListRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientTransactionListRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientTransactionReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListRequest(ClientTransactionListRequest other) : this() {
    headId_ = other.headId_;
    transactionIds_ = other.transactionIds_.Clone();
    Paging = other.paging_ != null ? other.Paging.Clone() : null;
    sorting_ = other.sorting_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListRequest Clone() {
    return new ClientTransactionListRequest(this);
  }

  /// <summary>Field number for the "head_id" field.</summary>
  public const int HeadIdFieldNumber = 1;
  private string headId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HeadId {
    get { return headId_; }
    set {
      headId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transaction_ids" field.</summary>
  public const int TransactionIdsFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_transactionIds_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> transactionIds_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> TransactionIds {
    get { return transactionIds_; }
  }

  /// <summary>Field number for the "paging" field.</summary>
  public const int PagingFieldNumber = 3;
  private global::ClientPagingControls paging_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientPagingControls Paging {
    get { return paging_; }
    set {
      paging_ = value;
    }
  }

  /// <summary>Field number for the "sorting" field.</summary>
  public const int SortingFieldNumber = 4;
  private static readonly pb::FieldCodec<global::ClientSortControls> _repeated_sorting_codec
      = pb::FieldCodec.ForMessage(34, global::ClientSortControls.Parser);
  private readonly pbc::RepeatedField<global::ClientSortControls> sorting_ = new pbc::RepeatedField<global::ClientSortControls>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::ClientSortControls> Sorting {
    get { return sorting_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientTransactionListRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientTransactionListRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HeadId != other.HeadId) return false;
    if(!transactionIds_.Equals(other.transactionIds_)) return false;
    if (!object.Equals(Paging, other.Paging)) return false;
    if(!sorting_.Equals(other.sorting_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HeadId.Length != 0) hash ^= HeadId.GetHashCode();
    hash ^= transactionIds_.GetHashCode();
    if (paging_ != null) hash ^= Paging.GetHashCode();
    hash ^= sorting_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HeadId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(HeadId);
    }
    transactionIds_.WriteTo(output, _repeated_transactionIds_codec);
    if (paging_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Paging);
    }
    sorting_.WriteTo(output, _repeated_sorting_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HeadId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HeadId);
    }
    size += transactionIds_.CalculateSize(_repeated_transactionIds_codec);
    if (paging_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Paging);
    }
    size += sorting_.CalculateSize(_repeated_sorting_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientTransactionListRequest other) {
    if (other == null) {
      return;
    }
    if (other.HeadId.Length != 0) {
      HeadId = other.HeadId;
    }
    transactionIds_.Add(other.transactionIds_);
    if (other.paging_ != null) {
      if (paging_ == null) {
        paging_ = new global::ClientPagingControls();
      }
      Paging.MergeFrom(other.Paging);
    }
    sorting_.Add(other.sorting_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          HeadId = input.ReadString();
          break;
        }
        case 18: {
          transactionIds_.AddEntriesFrom(input, _repeated_transactionIds_codec);
          break;
        }
        case 26: {
          if (paging_ == null) {
            paging_ = new global::ClientPagingControls();
          }
          input.ReadMessage(paging_);
          break;
        }
        case 34: {
          sorting_.AddEntriesFrom(input, _repeated_sorting_codec);
          break;
        }
      }
    }
  }

}

/// <summary>
/// A response that lists transactions from newest to oldest.
///
/// Statuses:
///   * OK - everything worked as expected
///   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
///   * NOT_READY - the validator does not yet have a genesis block
///   * NO_ROOT - the head block specified was not found
///   * NO_RESOURCE - no txns were found with the parameters specified
///   * INVALID_PAGING - the paging controls were malformed or out of range
///   * INVALID_SORT - the sorting controls were malformed or invalid
/// </summary>
public sealed partial class ClientTransactionListResponse : pb::IMessage<ClientTransactionListResponse> {
  private static readonly pb::MessageParser<ClientTransactionListResponse> _parser = new pb::MessageParser<ClientTransactionListResponse>(() => new ClientTransactionListResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientTransactionListResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientTransactionReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListResponse(ClientTransactionListResponse other) : this() {
    status_ = other.status_;
    transactions_ = other.transactions_.Clone();
    headId_ = other.headId_;
    Paging = other.paging_ != null ? other.Paging.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionListResponse Clone() {
    return new ClientTransactionListResponse(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::ClientTransactionListResponse.Types.Status status_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientTransactionListResponse.Types.Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "transactions" field.</summary>
  public const int TransactionsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::Transaction> _repeated_transactions_codec
      = pb::FieldCodec.ForMessage(18, global::Transaction.Parser);
  private readonly pbc::RepeatedField<global::Transaction> transactions_ = new pbc::RepeatedField<global::Transaction>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Transaction> Transactions {
    get { return transactions_; }
  }

  /// <summary>Field number for the "head_id" field.</summary>
  public const int HeadIdFieldNumber = 3;
  private string headId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HeadId {
    get { return headId_; }
    set {
      headId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "paging" field.</summary>
  public const int PagingFieldNumber = 4;
  private global::ClientPagingResponse paging_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientPagingResponse Paging {
    get { return paging_; }
    set {
      paging_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientTransactionListResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientTransactionListResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if(!transactions_.Equals(other.transactions_)) return false;
    if (HeadId != other.HeadId) return false;
    if (!object.Equals(Paging, other.Paging)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != 0) hash ^= Status.GetHashCode();
    hash ^= transactions_.GetHashCode();
    if (HeadId.Length != 0) hash ^= HeadId.GetHashCode();
    if (paging_ != null) hash ^= Paging.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Status != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    transactions_.WriteTo(output, _repeated_transactions_codec);
    if (HeadId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(HeadId);
    }
    if (paging_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Paging);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Status != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    size += transactions_.CalculateSize(_repeated_transactions_codec);
    if (HeadId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HeadId);
    }
    if (paging_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Paging);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientTransactionListResponse other) {
    if (other == null) {
      return;
    }
    if (other.Status != 0) {
      Status = other.Status;
    }
    transactions_.Add(other.transactions_);
    if (other.HeadId.Length != 0) {
      HeadId = other.HeadId;
    }
    if (other.paging_ != null) {
      if (paging_ == null) {
        paging_ = new global::ClientPagingResponse();
      }
      Paging.MergeFrom(other.Paging);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          status_ = (global::ClientTransactionListResponse.Types.Status) input.ReadEnum();
          break;
        }
        case 18: {
          transactions_.AddEntriesFrom(input, _repeated_transactions_codec);
          break;
        }
        case 26: {
          HeadId = input.ReadString();
          break;
        }
        case 34: {
          if (paging_ == null) {
            paging_ = new global::ClientPagingResponse();
          }
          input.ReadMessage(paging_);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientTransactionListResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Status {
      [pbr::OriginalName("STATUS_UNSET")] Unset = 0,
      [pbr::OriginalName("OK")] Ok = 1,
      [pbr::OriginalName("INTERNAL_ERROR")] InternalError = 2,
      [pbr::OriginalName("NOT_READY")] NotReady = 3,
      [pbr::OriginalName("NO_ROOT")] NoRoot = 4,
      [pbr::OriginalName("NO_RESOURCE")] NoResource = 5,
      [pbr::OriginalName("INVALID_PAGING")] InvalidPaging = 6,
      [pbr::OriginalName("INVALID_SORT")] InvalidSort = 7,
      [pbr::OriginalName("INVALID_ID")] InvalidId = 8,
    }

  }
  #endregion

}

/// <summary>
/// Fetches a specific txn by its id (header_signature) from the blockchain.
/// </summary>
public sealed partial class ClientTransactionGetRequest : pb::IMessage<ClientTransactionGetRequest> {
  private static readonly pb::MessageParser<ClientTransactionGetRequest> _parser = new pb::MessageParser<ClientTransactionGetRequest>(() => new ClientTransactionGetRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientTransactionGetRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientTransactionReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetRequest(ClientTransactionGetRequest other) : this() {
    transactionId_ = other.transactionId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetRequest Clone() {
    return new ClientTransactionGetRequest(this);
  }

  /// <summary>Field number for the "transaction_id" field.</summary>
  public const int TransactionIdFieldNumber = 1;
  private string transactionId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string TransactionId {
    get { return transactionId_; }
    set {
      transactionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientTransactionGetRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientTransactionGetRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TransactionId != other.TransactionId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (TransactionId.Length != 0) hash ^= TransactionId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (TransactionId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(TransactionId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (TransactionId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TransactionId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientTransactionGetRequest other) {
    if (other == null) {
      return;
    }
    if (other.TransactionId.Length != 0) {
      TransactionId = other.TransactionId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          TransactionId = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
/// A response that returns the txn specified by a ClientTransactionGetRequest.
///
/// Statuses:
///   * OK - everything worked as expected, txn has been fetched
///   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
///   * NO_RESOURCE - no txn with the specified id exists
/// </summary>
public sealed partial class ClientTransactionGetResponse : pb::IMessage<ClientTransactionGetResponse> {
  private static readonly pb::MessageParser<ClientTransactionGetResponse> _parser = new pb::MessageParser<ClientTransactionGetResponse>(() => new ClientTransactionGetResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientTransactionGetResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientTransactionReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetResponse(ClientTransactionGetResponse other) : this() {
    status_ = other.status_;
    Transaction = other.transaction_ != null ? other.Transaction.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientTransactionGetResponse Clone() {
    return new ClientTransactionGetResponse(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::ClientTransactionGetResponse.Types.Status status_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientTransactionGetResponse.Types.Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "transaction" field.</summary>
  public const int TransactionFieldNumber = 2;
  private global::Transaction transaction_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Transaction Transaction {
    get { return transaction_; }
    set {
      transaction_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientTransactionGetResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientTransactionGetResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (!object.Equals(Transaction, other.Transaction)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != 0) hash ^= Status.GetHashCode();
    if (transaction_ != null) hash ^= Transaction.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Status != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (transaction_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Transaction);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Status != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (transaction_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transaction);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientTransactionGetResponse other) {
    if (other == null) {
      return;
    }
    if (other.Status != 0) {
      Status = other.Status;
    }
    if (other.transaction_ != null) {
      if (transaction_ == null) {
        transaction_ = new global::Transaction();
      }
      Transaction.MergeFrom(other.Transaction);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          status_ = (global::ClientTransactionGetResponse.Types.Status) input.ReadEnum();
          break;
        }
        case 18: {
          if (transaction_ == null) {
            transaction_ = new global::Transaction();
          }
          input.ReadMessage(transaction_);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientTransactionGetResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Status {
      [pbr::OriginalName("STATUS_UNSET")] Unset = 0,
      [pbr::OriginalName("OK")] Ok = 1,
      [pbr::OriginalName("INTERNAL_ERROR")] InternalError = 2,
      [pbr::OriginalName("NO_RESOURCE")] NoResource = 5,
      [pbr::OriginalName("INVALID_ID")] InvalidId = 8,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
