#!/bin/bash

# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

set -e

directories="
    /var/lib/sawtooth
    /var/log/sawtooth
"

user="sawtooth"
group="sawtooth"

# Run on install and not upgrade
if [ "$1" = configure ] && [ -z "$2" ]; then
    if ! getent group $group > /dev/null; then
        addgroup --quiet --system $group
    fi

    if ! getent passwd $user > /dev/null; then
        adduser --quiet --system --ingroup $group $user
    fi

    for dir in $directories
    do
        chown -R $user:$group $dir
        chmod 750 $dir
    done

    chown -R root:root /etc/sawtooth
    chmod 755 /etc/sawtooth
    chmod 640 /etc/sawtooth/*.toml*
    chown root:$group /etc/sawtooth/*.toml*
    chown root:$group /etc/sawtooth/keys
    chmod 755 /etc/sawtooth/keys
fi
