# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  settings-tp:
    build:
      context: .
      dockerfile: families/settings/Dockerfile-installed
    image: sawtooth-settings-tp:${ISOLATION_ID}
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  intkey-tp-python:
    build:
      context: .
      dockerfile: sdk/examples/intkey_python/Dockerfile-installed
    image: sawtooth-intkey-tp-python:${ISOLATION_ID}
    container_name: sawtooth-intkey-tp-python-default
    depends_on:
      - validator
    entrypoint: intkey-tp-python -vv -C tcp://validator:4004

  xo-tp-python:
    build:
      context: .
      dockerfile: sdk/examples/xo_python/Dockerfile-installed
    image: sawtooth-xo-tp-python:${ISOLATION_ID}
    container_name: sawtooth-xo-tp-python-default
    depends_on:
      - validator
    entrypoint: xo-tp-python -vv -C tcp://validator:4004

  validator:
    build:
      context: .
      dockerfile: validator/Dockerfile-installed
    image: sawtooth-validator:${ISOLATION_ID}
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile-installed
    image: sawtooth-rest-api:${ISOLATION_ID}
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    build:
      context: .
      dockerfile: ci/sawtooth-shell-installed
    image: sawtooth-shell:${ISOLATION_ID}
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  admin-tools:
    build:
      context: .
      dockerfile: adm/Dockerfile-installed
    image: sawtooth-admin-tools:${ISOLATION_ID}
    container_name: sawtooth-admin-tools

  sawtooth-cli:
    build:
      context: .
      dockerfile: cli/Dockerfile-installed
    image: sawtooth-cli:${ISOLATION_ID}
    container_name: sawtooth-cli-default

  poet-cli:
    build:
      context: .
      dockerfile: consensus/poet/cli/Dockerfile-installed
    image: sawtooth-poet-cli:${ISOLATION_ID}
    container_name: sawtooth-poet-cli-default

  poet-common:
    build:
      context: .
      dockerfile: consensus/poet/common/Dockerfile-installed
    image: sawtooth-poet-common:${ISOLATION_ID}
    container_name: sawtooth-poet-common-default

  poet-core:
    build:
      context: .
      dockerfile: consensus/poet/core/Dockerfile-installed
    image: sawtooth-poet-core:${ISOLATION_ID}
    container_name: sawtooth-poet-core-default

  poet-families:
    build:
      context: .
      dockerfile: consensus/poet/families/Dockerfile-installed
    image: sawtooth-poet-validator-registry-tp:${ISOLATION_ID}
    container_name: sawtooth-poet-families-default

  poet-sgx:
    build:
      context: .
      dockerfile: consensus/poet/sgx/Dockerfile-installed
    image: sawtooth-poet-sgx:${ISOLATION_ID}
    container_name: sawtooth-poet-sgx-default

  poet-simulator:
    build:
      context: .
      dockerfile: consensus/poet/simulator/Dockerfile-installed
    image: sawtooth-poet-simulator:${ISOLATION_ID}
    container_name: sawtooth-poet-simulator-default

  block-info-tp:
    build:
      context: .
      dockerfile: families/block_info/python/Dockerfile-installed
    image: sawtooth-block-info-tp:${ISOLATION_ID}
    container_name: sawtooth-block-info-tp-default

  identity-tp:
    build:
      context: .
      dockerfile: families/identity/Dockerfile-installed
    image: sawtooth-identity-tp:${ISOLATION_ID}
    container_name: sawtooth-identity-tp-default

  smallbank-tp-go:
    build:
      context: .
      dockerfile: families/smallbank/smallbank_go/Dockerfile-installed
    image: sawtooth-smallbank-tp-go:${ISOLATION_ID}
    container_name: sawtooth-smallbank-tp-go-default

  sawtooth-intkey-tp-go:
    build:
      context: .
      dockerfile: sdk/examples/intkey_go/Dockerfile-installed
    image: sawtooth-intkey-tp-go:${ISOLATION_ID}
    container_name: sawtooth-intkey-tp-go-default

  sawtooth-noop-tp-go:
    build:
      context: .
      dockerfile: sdk/examples/noop_go/Dockerfile-installed
    image: sawtooth-noop-tp-go:${ISOLATION_ID}
    container_name: sawtooth-noop-tp-go-default

  sawtooth-xo-tp-go:
    build:
      context: .
      dockerfile: sdk/examples/xo_go/Dockerfile-installed
    image: sawtooth-xo-tp-go:${ISOLATION_ID}
    container_name: sawtooth-xo-tp-go-default

  python-sdk:
    build:
      context: .
      dockerfile: sdk/python/Dockerfile-installed
    image: sawtooth-sdk-python:${ISOLATION_ID}
    container_name: sawtooth-sdk-python-default

  signing:
    build:
      context: .
      dockerfile: signing/Dockerfile-installed
    image: sawtooth-signing:${ISOLATION_ID}
    container_name: sawtooth-signing-default

  ias_client:
    build:
      context: .
      dockerfile: utility/ias_client/Dockerfile-installed
    image: sawtooth-ias-client:${ISOLATION_ID}
    container_name: sawtooth-ias-client-default

  ias_proxy:
    build:
      context: .
      dockerfile: utility/ias_proxy/Dockerfile-installed
    image: sawtooth-ias-proxy:${ISOLATION_ID}
    container_name: sawtooth-ias-proxy-default

  intkey-tests:
    build:
      context: .
      dockerfile: sdk/examples/intkey_python/Dockerfile-tests-installed
    image: sawtooth-intkey-tests:${ISOLATION_ID}
    container_name: sawtooth-intkey-tests-default

  xo-tests:
    build:
      context: .
      dockerfile: sdk/examples/xo_python/Dockerfile-tests-installed
    image: sawtooth-xo-tests:${ISOLATION_ID}
    container_name: sawtooth-xo-tests-default

  integration:
    build:
      context: .
      dockerfile: integration/Dockerfile-installed
    image: sawtooth-integration:${ISOLATION_ID}
    container_name: sawtooth-integration-default

  smallbank-workload:
    build:
      context: .
      dockerfile: perf/smallbank_workload/Dockerfile-installed
    image: sawtooth-smallbank-workload:${ISOLATION_ID}
    container_name: sawtooth-smallbank-workload

  devmode-rust:
    build:
      context: .
      dockerfile: sdk/examples/devmode_rust/Dockerfile-installed
    image: sawtooth-devmode-rust:${ISOLATION_ID}
    container_name: sawtooth-devmode-rust
