# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  settings-tp:
    build:
      context: .
      dockerfile: families/settings/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-settings-tp:${ISOLATION_ID}
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  validator:
    build:
      context: .
      dockerfile: validator/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-validator:${ISOLATION_ID}
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  rest-api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-rest-api:${ISOLATION_ID}
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    build:
      context: .
      dockerfile: ci/sawtooth-shell-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-shell:${ISOLATION_ID}
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

# ---== Intkey and XO TPs are in a separate repo ==---

  intkey-tp-python:
    image: hyperledger/sawtooth-intkey-tp-python:nightly
    container_name: sawtooth-intkey-tp-python-default
    depends_on:
      - validator
    entrypoint: intkey-tp-python -vv -C tcp://validator:4004

  xo-tp-python:
    image: hyperledger/sawtooth-xo-tp-python:nightly
    container_name: sawtooth-xo-tp-python-default
    depends_on:
      - validator
    entrypoint: xo-tp-python -vv -C tcp://validator:4004

# ---== Back to repo stuff ==----

  admin-tools:
    build:
      context: .
      dockerfile: adm/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-admin-tools:${ISOLATION_ID}
    container_name: sawtooth-admin-tools

  sawtooth-cli:
    build:
      context: .
      dockerfile: cli/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-cli:${ISOLATION_ID}
    container_name: sawtooth-cli-default

  block-info-tp:
    build:
      context: .
      dockerfile: families/block_info/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-block-info-tp:${ISOLATION_ID}
    container_name: sawtooth-block-info-tp-default

  identity-tp:
    build:
      context: .
      dockerfile: families/identity/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-identity-tp:${ISOLATION_ID}
    container_name: sawtooth-identity-tp-default

  integration:
    build:
      context: .
      dockerfile: integration/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-integration:${ISOLATION_ID}
    container_name: sawtooth-integration-default

  smallbank-workload:
    build:
      context: .
      dockerfile: perf/smallbank_workload/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-smallbank-workload:${ISOLATION_ID}
    container_name: sawtooth-smallbank-workload

  intkey-workload:
    build:
      context: .
      dockerfile: perf/intkey_workload/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-intkey-workload:${ISOLATION_ID}
    container_name: sawtooth-intkey-workload

  smallbank-tp-rust:
    build:
      context: .
      dockerfile: families/smallbank/smallbank_rust/Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-smallbank-tp-rust:${ISOLATION_ID}
    container_name: sawtooth-tp-rust

  sawtooth-meta:
    build:
      context: .
      dockerfile: ci/sawtooth-meta-${DISTRO}
    image: sawtooth-meta:${ISOLATION_ID}
    container_name: sawtooth-meta

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:nightly
    container_name: sawtooth-devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL
