#!/bin/bash

set -e
          
root=/project 
build_dir=$root/build-sles
release=sawtoothlake-x.y.z-sles-packages
tmp_dir=/tmp/sawtooth-install-$$

if [ ! -f $build_dir/$release.tar.bz2 ]; then
    echo "No such file: $build_dir/$release.tar.bz2"
    exit 1
fi

echo "Removing old installation..."
zypper remove -y \
    SawtoothLakeLedger \
    SawtoothLakeMarket \
    SawtoothLakeValidator \
    || /bin/true

zypper addrepo \
        http://download.opensuse.org/repositories/devel:/libraries:/c_c++/openSUSE_13.2/devel:libraries:c_c++.repo \
	|| /bin/true

zypper addrepo \
        http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_13.2/devel:languages:python.repo \
	|| /bin/true

zypper refresh

echo "Creating $tmp_dir..."
mkdir -p $tmp_dir

cd $tmp_dir
tar xvfj $build_dir/$release.tar.bz2
cd $release
ls -l
zypper install -y *.rpm

cd $build_dir
rm -rf $tmp_dir
