# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sawtooth_poet/protobuf/validator_registry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sawtooth_poet/protobuf/validator_registry.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n/sawtooth_poet/protobuf/validator_registry.proto\"r\n\rValidatorInfo\x12\x12\n\nregistered\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12 \n\x0bsignup_info\x18\x04 \x01(\x0b\x32\x0b.SignUpInfo\x12\x11\n\tblock_num\x18\x05 \x01(\x05\"P\n\nSignUpInfo\x12\x17\n\x0fpoet_public_key\x18\x01 \x01(\t\x12\x12\n\nproof_data\x18\x02 \x01(\t\x12\x15\n\ranti_sybil_id\x18\x03 \x01(\t\"Y\n\x0cValidatorMap\x12$\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x13.ValidatorMap.Entry\x1a#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"w\n\x18ValidatorRegistryPayload\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12 \n\x0bsignup_info\x18\x04 \x01(\x0b\x32\x0b.SignUpInfo\x12\x11\n\tblock_num\x18\x05 \x01(\x05\x42\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VALIDATORINFO = _descriptor.Descriptor(
  name='ValidatorInfo',
  full_name='ValidatorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registered', full_name='ValidatorInfo.registered', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ValidatorInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ValidatorInfo.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signup_info', full_name='ValidatorInfo.signup_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_num', full_name='ValidatorInfo.block_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=165,
)


_SIGNUPINFO = _descriptor.Descriptor(
  name='SignUpInfo',
  full_name='SignUpInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poet_public_key', full_name='SignUpInfo.poet_public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proof_data', full_name='SignUpInfo.proof_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anti_sybil_id', full_name='SignUpInfo.anti_sybil_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=247,
)


_VALIDATORMAP_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='ValidatorMap.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ValidatorMap.Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ValidatorMap.Entry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=338,
)

_VALIDATORMAP = _descriptor.Descriptor(
  name='ValidatorMap',
  full_name='ValidatorMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='ValidatorMap.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VALIDATORMAP_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=338,
)


_VALIDATORREGISTRYPAYLOAD = _descriptor.Descriptor(
  name='ValidatorRegistryPayload',
  full_name='ValidatorRegistryPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='ValidatorRegistryPayload.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ValidatorRegistryPayload.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ValidatorRegistryPayload.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signup_info', full_name='ValidatorRegistryPayload.signup_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_num', full_name='ValidatorRegistryPayload.block_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=459,
)

_VALIDATORINFO.fields_by_name['signup_info'].message_type = _SIGNUPINFO
_VALIDATORMAP_ENTRY.containing_type = _VALIDATORMAP
_VALIDATORMAP.fields_by_name['entries'].message_type = _VALIDATORMAP_ENTRY
_VALIDATORREGISTRYPAYLOAD.fields_by_name['signup_info'].message_type = _SIGNUPINFO
DESCRIPTOR.message_types_by_name['ValidatorInfo'] = _VALIDATORINFO
DESCRIPTOR.message_types_by_name['SignUpInfo'] = _SIGNUPINFO
DESCRIPTOR.message_types_by_name['ValidatorMap'] = _VALIDATORMAP
DESCRIPTOR.message_types_by_name['ValidatorRegistryPayload'] = _VALIDATORREGISTRYPAYLOAD

ValidatorInfo = _reflection.GeneratedProtocolMessageType('ValidatorInfo', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATORINFO,
  __module__ = 'sawtooth_poet.protobuf.validator_registry_pb2'
  # @@protoc_insertion_point(class_scope:ValidatorInfo)
  ))
_sym_db.RegisterMessage(ValidatorInfo)

SignUpInfo = _reflection.GeneratedProtocolMessageType('SignUpInfo', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPINFO,
  __module__ = 'sawtooth_poet.protobuf.validator_registry_pb2'
  # @@protoc_insertion_point(class_scope:SignUpInfo)
  ))
_sym_db.RegisterMessage(SignUpInfo)

ValidatorMap = _reflection.GeneratedProtocolMessageType('ValidatorMap', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _VALIDATORMAP_ENTRY,
    __module__ = 'sawtooth_poet.protobuf.validator_registry_pb2'
    # @@protoc_insertion_point(class_scope:ValidatorMap.Entry)
    ))
  ,
  DESCRIPTOR = _VALIDATORMAP,
  __module__ = 'sawtooth_poet.protobuf.validator_registry_pb2'
  # @@protoc_insertion_point(class_scope:ValidatorMap)
  ))
_sym_db.RegisterMessage(ValidatorMap)
_sym_db.RegisterMessage(ValidatorMap.Entry)

ValidatorRegistryPayload = _reflection.GeneratedProtocolMessageType('ValidatorRegistryPayload', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATORREGISTRYPAYLOAD,
  __module__ = 'sawtooth_poet.protobuf.validator_registry_pb2'
  # @@protoc_insertion_point(class_scope:ValidatorRegistryPayload)
  ))
_sym_db.RegisterMessage(ValidatorRegistryPayload)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030sawtooth.config.protobufP\001'))
# @@protoc_insertion_point(module_scope)
