#!/bin/bash

set -e

user="sawtooth"
group="sawtooth"

if ! getent passwd $user > /dev/null; then
    adduser --quiet --system $user
fi

if ! getent group $group > /dev/null; then
    addgroup --quiet --system $group
fi
