#!/bin/bash

set -e

root=/project
build_dir=$root/build
pkg_dir=$build_dir/packages
release=sawtoothlake-x.y.z-ubuntu-packages

mkdir -p $build_dir
mkdir -p $pkg_dir

apt-get install -y -q \
    python-twisted \
    python-twisted-web \
    python-dev \
    python-setuptools \
    g++ \
    swig3.0 \
    libjson0 \
    libjson0-dev \
    libcrypto++-dev \
    git \
    python-all-dev \
    python-stdeb

if [ ! -f $pkg_dir/python-cbor_0.1.24-1_amd64.deb ]; then
    cd $build_dir
    wget https://pypi.python.org/packages/source/c/cbor/cbor-0.1.24.tar.gz
    tar xvfz cbor-0.1.24.tar.gz
    cd cbor-0.1.24
    python setup.py --command-packages=stdeb.command bdist_deb
    cp deb_dist/python-cbor*.deb $pkg_dir
fi

if [ ! -f $pkg_dir/python-colorlog_2.6.0-1_all.deb ]; then
    cd $build_dir
    wget https://pypi.python.org/packages/source/c/colorlog/colorlog-2.6.0.tar.gz
    tar xvfz colorlog-2.6.0.tar.gz
    cd colorlog-2.6.0
    python setup.py --command-packages=stdeb.command bdist_deb
    cp deb_dist/python-colorlog*.deb $pkg_dir
fi

if [ ! -f $pkg_dir/python-pybitcointools_1.1.15-1_all.deb ]; then
    cd $build_dir
    wget https://pypi.python.org/packages/source/p/pybitcointools/pybitcointools-1.1.15.tar.gz
    tar xvfz pybitcointools-1.1.15.tar.gz
    cd pybitcointools-1.1.15
    python setup.py --command-packages=stdeb.command bdist_deb
    cp deb_dist/python-pybitcointools*.deb $pkg_dir
fi

rm -f $pkg_dir/python-sawtooth*.deb

cd $root/sawtooth-core
python setup.py clean --all
python setup.py --command-packages=stdeb.command bdist_deb
cp deb_dist/python-sawtooth-core*.deb $pkg_dir

cd $root/sawtooth-mktplace
python setup.py clean --all
python setup.py --command-packages=stdeb.command bdist_deb
cp deb_dist/python-sawtooth-mktplace*.deb $pkg_dir

cd $root/sawtooth-validator
python setup.py clean --all
python setup.py --command-packages=stdeb.command bdist_deb
cp deb_dist/python-sawtooth-validator*.deb $pkg_dir

cd $build_dir
rsync -avH $pkg_dir/ $release/
tar cvfj $release.tar.bz2 $release

echo "-----"
echo "Created:"
echo "$build_dir/$release.tar.bz2"
