#!/bin/bash

set -e
          
root=/project 
build_dir=$root/build
release=sawtoothlake-x.y.z-ubuntu-packages
tmp_dir=/tmp/sawtooth-install-$$

if [ ! -f $build_dir/$release.tar.bz2 ]; then
    echo "No such file: $build_dir/$release.tar.bz2"
    exit 1
fi

echo "Removing old installation..."
dpkg -r \
    python-sawtoothlakeledger \
    python-sawtoothlakemarket \
    python-sawtoothlakevalidator

echo "Creating $tmp_dir..."
mkdir -p $tmp_dir

cd $tmp_dir
tar xvfj $build_dir/$release.tar.bz2
cd $release
ls -l
dpkg -i *.deb

cd $build_dir
rm -rf $tmp_dir
