#!/bin/bash

set -e


if ! getent passwd sawtooth > /dev/null; then
    adduser --quiet --system sawtooth
fi

if ! getent group sawtooth > /dev/null; then
    addgroup --quiet --system sawtooth
fi


chown -R sawtooth:sawtooth /var/lib/sawtooth-validator
chown -R sawtooth:sawtooth /var/log/sawtooth-validator
chown -R sawtooth:sawtooth /var/run/sawtooth-validator
