# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# In first window, run:
#   $ cd sawtooth-core
#   $ ./bin/build_all -l go -l python
#   $ docker-compose -f docker/compose/sawtooth-seth.yaml up
#
# In second window, run:
#   $ docker exec -it seth-client bash

version: "3"

services:

  seth-tp:
    image: sawtooth-dev-seth:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
    depends_on:
      - validator
    command: seth-tp -vv tcp://validator:4004
    stop_signal: SIGKILL

  block-info-tp:
    image: sawtooth-block-info-tp:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
    depends_on:
      - validator
    command: block-info-tp -vv tcp://validator:4004
    stop_signal: SIGKILL

  settings-tp:
    image: sawtooth-settings-tp:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
    depends_on:
      - validator
    entrypoint: settings-tp -vv tcp://validator:4004

  validator:
    image: sawtooth-validator:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    ports:
      - 4004
      - 8800
    command: "bash -c \"\
        sawtooth admin keygen && \
        sawtooth config genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawtooth config proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.validator.batch_injectors=block_info \
          -o config.batch && \
        sawtooth admin genesis \
          config-genesis.batch config.batch && \
        sawtooth-validator --endpoint tcp://validator:8800 -v \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
    \""
    environment:
      PYTHONPATH: "/project/sawtooth-core/families/block_info"
    stop_signal: SIGKILL

  rest-api:
    image: sawtooth-rest-api:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
      - 8080
    ports:
      - 8080:8080
    depends_on:
     - validator
    command: sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8080
    stop_signal: SIGKILL

  seth:
    container_name: seth
    image: sawtooth-dev-seth:latest
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 3030
      - 8080
    ports:
      - 3030:3030
    working_dir: "/project/sawtooth-core"
    command: "bash -c \"
        seth init http://rest-api:8080 && \
        tail -f /dev/null\""
    stop_signal: SIGKILL
