# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2.1"

services:

  settings-tp:
    image: sawtooth-settings-tp:latest
    volumes:
      - ../../:/project/sawtooth-core
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    command: settings-tp -vv tcp://validator:4004

  smallbank-tp-go:
    image: sawtooth-smallbank-tp-go:latest
    container_name: sawtooth-smallbank-tp-go-default
    volumes:
      - ../../:/project/sawtooth-core
    depends_on:
      - validator
    command: smallbank-tp-go -vv tcp://validator:4004

  validator:
    image: sawtooth-validator-mounted:latest
    container_name: sawtooth-validator-mounted
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 4004
      - 8800
    ports:
      - "4004:4004"
      - "8800:8800"
    command: "bash -c \"\
        (telegraf &) && \
        sawtooth admin keygen && \
        sawtooth keygen && \
        sawtooth config genesis && \
        sawtooth admin genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    image: sawtooth-rest-api:latest
    container_name: sawtooth-rest-api-default
    volumes:
      - ../../:/project/sawtooth-core
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
     - validator
    command: sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8080 --opentsdb-url http://influxdb:8086 --opentsdb-db metrics

  influxdb:
    image: sawtooth-stats-influxdb:latest
    container_name: sawtooth-stats-influxdb-default
    ports:
      - "8086:8086"
    stop_signal: SIGKILL

  grafana:
    image: sawtooth-stats-grafana:latest
    container_name: sawtooth-stats-grafana-default
    ports:
      - "3000:3000"
    volumes:
      - ../../:/project/sawtooth-core
    stop_signal: SIGKILL
